name: iOS Unit Tests

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - .github/workflows/ios-unit-tests.yml
      - ios/**
      - packages/**/ios/**
      - tools/src/dynamic-macros/**
      - tools/src/commands/IosGenerateDynamicMacros.ts
      - tools/src/commands/IosNativeUnitTests.ts
      - tools/src/commands/NativeUnitTests.ts
      - secrets/**
      - fastlane/**
      - Gemfile.lock
      - .ruby-version
  push:
    branches: [main]
    paths:
      - .github/workflows/ios-unit-tests.yml
      - ios/**
      - packages/**/ios/**
      - tools/src/dynamic-macros/**
      - tools/src/commands/IosGenerateDynamicMacros.ts
      - tools/src/commands/IosNativeUnitTests.ts
      - tools/src/commands/NativeUnitTests.ts
      - secrets/**
      - fastlane/**
      - Gemfile.lock
      - .ruby-version

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-11
    timeout-minutes: 60
    steps:
      - name: 👀 Checkout a ref for the event
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: 🔨 Switch to Xcode 13.0
        run: sudo xcode-select --switch /Applications/Xcode_13.0.app
      - name: 🍺 Setup Homebrew
        run: brew install git-crypt
      - name: 🔓 Decrypt secrets if possible
        env:
          GIT_CRYPT_KEY_BASE64: ${{ secrets.GIT_CRYPT_KEY_BASE64 }}
        run: |
          if [[ ${GIT_CRYPT_KEY_BASE64:-unset} = unset ]]; then
            echo 'git-crypt key not present in environment'
          else
            git crypt unlock <(echo $GIT_CRYPT_KEY_BASE64 | base64 --decode)
          fi
      - name: ➕ Add bin to $GITHUB_PATH
        run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: ♻️ Restore workspace node modules
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: |
            # See "workspaces" → "packages" in the root package.json for the source of truth of
            # which node_modules are affected by the root yarn.lock
            node_modules
            apps/*/node_modules
            home/node_modules
            packages/*/node_modules
            packages/@expo/*/node_modules
            packages/@unimodules/*/node_modules
            react-native-lab/react-native/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: 🧶 Yarn install
        run: yarn install --frozen-lockfile
      - name: ♻️ Restore node modules in tools
        uses: actions/cache@v2
        with:
          path: tools/node_modules
          key: ${{ runner.os }}-tools-modules-${{ hashFiles('tools/yarn.lock') }}
      - name: 🏭 Generating dynamic macros
        run: expotools ios-generate-dynamic-macros
      - name: 💎 Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: ♻️ Restore ios/Pods from cache
        uses: actions/cache@v2
        with:
          path: 'ios/Pods'
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
      - name: 🥥 Install CocoaPods in `ios`
        run: pod install
        working-directory: ios
      - name: ♻️ Restore apps/bare-expo/ios/Pods from cache
        uses: actions/cache@v2
        with:
          path: 'apps/bare-expo/ios/Pods'
          key: ${{ runner.os }}-bare-expo-pods-${{ hashFiles('apps/bare-expo/ios/Podfile.lock') }}
      - name: 🥥 Install pods in apps/bare-expo/ios
        run: pod install
        working-directory: apps/bare-expo/ios
      - name: 🥷 Run native iOS unit tests
        timeout-minutes: 45
        run: expotools native-unit-tests --platform ios
